[package]
name = "kanau"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "General purpose functional programming library for Rust."

[dependencies]
tokio = {version = "1", features = ["full"]}
tokio-stream = {version = "0.1.17", features = ["full"]}
futures = "0.3.31"