[package]
name = "kanau-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
proc-macro2 = "1.0"
convert_case = "0.8.0"
quote = "1"
regex = "1.11.1"